### ISSUE TITLE
Maximun call stack size

### ISSUE THREAD

**Issue by jaime-franco** [yannisgu/dpd-jobs#14]
Hi i'm using dpd-jobs in my mac and trying to run a console.log("Test"); and i get this error everytime i hit play or the cron job is executed : 

PUT /__resources/welldone { [RangeError: Maximum call stack size exceeded]
  domain: 
   { domain: null,
     _events: { error: [Function] },
     _maxListeners: 10,
     members: [ [Object], [Object] ] },
  domainThrown: true }
Failed to start MongoDB (Make sure 'mongod' are in your $PATH or use dpd --mongod option. Ref: http://docs.deployd.com/docs/basics/cli.html)

**Comment by justmiles** [comment]
There seems to be an issue passing in `request

**Comment by fotoflo** [comment]
Im getting this issue too. Any solution?

**Comment by PJCzx** [comment]
Looks like a problem I detailed here : https://github.com/yannisgu/dpd-jobs/issues/1
Anything new ?

**Comment by yannisgu** [comment]
Hey Guys

Thanks for reporting this. I fixed the issue 5147371761c9dc75db4b410df24b45840f1bacbf and will release 0.14 of dpd-jobs right now which will fix this.

**Comment by PJCzx** [comment]
It works ;) Thx !
